import "./globals.css";
import { Inter } from "next/font/google";
import { ReduxProvider } from "./store/provider";
import { Navbars } from "./components/navbar/Navbars";
import { Navbar } from "./components/navbar-2/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}`}
        style={{ backgroundColor: "#f2f3ed" }}
        dir="rtl"
      >
        <ReduxProvider>
          <Navbar />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
