import "./globals.css";
import { Inter } from "next/font/google";
import { ReduxProvider } from "./_store/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${inter.className}`}
        // style={{ backgroundColor: "#f2f3ed" }}
        dir="ltr"
      >
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
